In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

import sklearn
from sklearn import neighbors, datasets, svm
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

import matplotlib
#matplotlib.use('GTKAgg')
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.colors import ListedColormap
%matplotlib inline
matplotlib.rcParams.update({'font.size': 18})

pip install xlrd==1.2.0.  (latest version of xlrd only imports .xls 

In [267]:
#df = pd.read_excel ('Black-Box-Optimization/Data/number_of_parameters_2.xlsx')
                  

In [268]:
df = pd.read_excel ('Black-Box-Optimization/Data/All Data combined.xlsx')

<ipython-input-268-dc8600ecbd90>:1: FutureWarning: Your version of xlrd is 1.2.0. In xlrd >= 2.0, only the xls format is supported. As a result, the openpyxl engine will be used if it is installed and the engine argument is not specified. Install openpyxl instead.
  df = pd.read_excel ('Black-Box-Optimization/Data/All Data combined.xlsx')


In [269]:
print(len(df))
print(df.head())

1350
   Unnamed: 0  number of trials  number of parameters type of function  \
0         0.0                16                     2             Trig   
1         1.0                13                     2             Trig   
2         2.0                10                     2             Trig   
3         3.0                18                     2             Trig   
4         4.0                11                     2             Trig   

   accuracy [calc. max/ actual max]  time per trial [s] type_of_opt  \
0                          0.732417            0.009824       CmaEs   
1                          0.983980            0.008316       CmaEs   
2                          0.638160            0.007854       CmaEs   
3                          0.952784            0.009196       CmaEs   
4                          0.284646            0.007938       CmaEs   

   assigned_class  
0               0  
1               0  
2               0  
3               0  
4               0  


In [15]:
# replace zeroes
zero_not_accepted = ['number of parameters', 'type of function', 'accuracy [calc. max/ actual max]', 'time per trial [s]', 'type_of_opt']

for column in zero_not_accepted:
    df[column] = df[column].replace(0, np.NaN)
    

In [6]:
# split dataset
# X = df.iloc[:,0:6]
# y = df.iloc[:,5:6]
#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

In [270]:
X = df[['number of trials','accuracy [calc. max/ actual max]','time per trial [s]']]
y = df['assigned_class']

print(len(y))

1350


In [271]:
# split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=14) #14 is seed

print(len(y_train), len(y_test))

1080 270


In [166]:
#Feature scaling
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [216]:
plt.hist(X_train[:,1])

TypeError: '(slice(None, None, None), 1)' is an invalid key

In [272]:
K_neighbors = 2

In [273]:
#Define the model: Init K-NN
# We create an instance of Neighbours Classifier and fit it to the training data.
# if you set weights = 'distance' here you will have a weighted KNN classifier
clf = neighbors.KNeighborsClassifier(K_neighbors, weights='distance')

# Here we fit it to the data - it figures out the classes and 
# which training X points belong to each class in Y 
clf.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2, weights='distance')

In [274]:
print(clf.classes_, clf.effective_metric_, clf.n_samples_fit_)

[0 1 2 3 4] euclidean 1080


In [275]:
# Predict the test set results
y_test_predicted = clf.predict(X_test)
y_test_probabilities = clf.predict_proba(X_test)
mean_accuracy = clf.score(X_test, y_test)

print("predicted classes", y_test_predicted)
print("KNN probability of belonging to class",y_test_probabilities)
print("Mean accuracy of prediction", mean_accuracy)


predicted classes [4 2 2 0 3 0 2 1 0 2 0 1 1 3 0 0 3 2 0 3 3 3 1 1 2 2 1 1 1 3 0 1 3 0 2 0 3
 3 2 3 0 1 1 3 3 0 0 0 1 0 3 1 3 3 3 0 3 4 0 2 0 1 0 0 0 0 2 0 0 3 2 3 0 3
 0 3 2 0 3 2 1 2 2 1 3 2 3 0 0 0 2 1 1 3 0 0 0 1 1 1 3 0 0 1 2 0 0 3 2 0 1
 3 3 2 3 3 2 2 0 1 0 3 4 0 2 0 3 1 1 1 2 0 0 4 0 0 0 0 0 3 0 2 0 2 0 3 3 1
 0 0 1 0 0 2 2 1 1 2 1 3 1 3 2 2 3 1 2 2 1 4 1 1 0 2 0 2 2 3 0 0 1 1 3 1 0
 0 0 1 0 3 2 4 2 3 3 0 2 0 4 0 3 2 0 0 1 3 0 3 0 3 3 1 4 3 3 1 3 2 0 3 2 1
 0 2 3 0 0 1 0 2 3 4 3 1 2 0 0 2 0 0 2 3 0 3 3 3 1 2 1 0 1 1 1 1 0 0 4 0 3
 1 4 3 2 2 0 0 1 3 3 3]
KNN probability of belonging to class [[0.         0.         0.         0.         1.        ]
 [0.41544437 0.         0.58455563 0.         0.        ]
 [0.         0.23496414 0.76503586 0.         0.        ]
 ...
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.         1.         0.        ]]
Mean accuracy of prediction 0.50370370370

In [276]:
sklearn.metrics.mean_squared_error(y_test, y_test_predicted)

1.3777777777777778

In [277]:
y_test

1297    4
978     3
151     0
417     2
1073    3
       ..
804     1
807     1
1182    3
1077    3
1203    3
Name: assigned_class, Length: 270, dtype: int64

In [278]:
y_test_predicted

array([4, 2, 2, 0, 3, 0, 2, 1, 0, 2, 0, 1, 1, 3, 0, 0, 3, 2, 0, 3, 3, 3,
       1, 1, 2, 2, 1, 1, 1, 3, 0, 1, 3, 0, 2, 0, 3, 3, 2, 3, 0, 1, 1, 3,
       3, 0, 0, 0, 1, 0, 3, 1, 3, 3, 3, 0, 3, 4, 0, 2, 0, 1, 0, 0, 0, 0,
       2, 0, 0, 3, 2, 3, 0, 3, 0, 3, 2, 0, 3, 2, 1, 2, 2, 1, 3, 2, 3, 0,
       0, 0, 2, 1, 1, 3, 0, 0, 0, 1, 1, 1, 3, 0, 0, 1, 2, 0, 0, 3, 2, 0,
       1, 3, 3, 2, 3, 3, 2, 2, 0, 1, 0, 3, 4, 0, 2, 0, 3, 1, 1, 1, 2, 0,
       0, 4, 0, 0, 0, 0, 0, 3, 0, 2, 0, 2, 0, 3, 3, 1, 0, 0, 1, 0, 0, 2,
       2, 1, 1, 2, 1, 3, 1, 3, 2, 2, 3, 1, 2, 2, 1, 4, 1, 1, 0, 2, 0, 2,
       2, 3, 0, 0, 1, 1, 3, 1, 0, 0, 0, 1, 0, 3, 2, 4, 2, 3, 3, 0, 2, 0,
       4, 0, 3, 2, 0, 0, 1, 3, 0, 3, 0, 3, 3, 1, 4, 3, 3, 1, 3, 2, 0, 3,
       2, 1, 0, 2, 3, 0, 0, 1, 0, 2, 3, 4, 3, 1, 2, 0, 0, 2, 0, 0, 2, 3,
       0, 3, 3, 3, 1, 2, 1, 0, 1, 1, 1, 1, 0, 0, 4, 0, 3, 1, 4, 3, 2, 2,
       0, 0, 1, 3, 3, 3])

In [279]:
X_train[:,0]

TypeError: '(slice(None, None, None), 0)' is an invalid key

In [280]:
# Evaluate Model
cm = confusion_matrix(y_test, y_test_predicted)
print(cm)

[[35 18 13  3  0]
 [20 21 12  3  0]
 [23 11 17  5  0]
 [ 8  5  8 53  1]
 [ 1  0  1  2 10]]


In [ ]:
# classifier = KNeighborsClassifier(n_neighbors=1, p=2, metric='euclidean')

In [61]:
# Create color maps


In [296]:
model = svm.SVC(kernel='linear',C=1000,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test, y_test)
y_1_test_predicted = model.predict(X_test)
sklearn.metrics.mean_squared_error(y_test, y_1_test_predicted)

1.3074074074074074

In [297]:
model.score(X_test, y_test)

0.6111111111111112

Hyper parameter Tuning 

In [282]:
kernels = ['rbf','linear']
C = [1,10,20,30,40,50,60,70,80,90,100]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'), X, df['type_of_opt'], cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
        
avg_scores

{'rbf_1': 0.32962962962962966,
 'rbf_10': 0.35703703703703704,
 'rbf_20': 0.3659259259259259,
 'rbf_30': 0.3733333333333333,
 'rbf_40': 0.3711111111111111,
 'rbf_50': 0.3740740740740741,
 'rbf_60': 0.3851851851851852,
 'rbf_70': 0.385925925925926,
 'rbf_80': 0.3881481481481482,
 'rbf_90': 0.38666666666666666,
 'rbf_100': 0.3911111111111111,
 'linear_1': 0.3311111111111111,
 'linear_10': 0.40518518518518515,
 'linear_20': 0.42370370370370364,
 'linear_30': 0.4422222222222222,
 'linear_40': 0.4444444444444445,
 'linear_50': 0.4637037037037037,
 'linear_60': 0.4666666666666666,
 'linear_70': 0.47259259259259256,
 'linear_80': 0.482962962962963,
 'linear_90': 0.4837037037037037,
 'linear_100': 0.4992592592592593}

Hyper parameter Tunning with GridSearchCV

In [283]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20,30,40,50,60,70,80,90,100],
    'kernel':['rbf','linear']
}, cv=5, return_train_score=False)

clf.fit(X,df['type_of_opt'])
clf.cv_results_

{'mean_fit_time': array([0.06960578, 0.23395162, 0.07710428, 0.5546432 , 0.07461338,
        0.83435845, 0.07788959, 1.24590383, 0.07840762, 1.76379213,
        0.08080807, 1.9652317 , 0.08673525, 2.35163116, 0.08739781,
        2.53706274, 0.08587966, 2.76544185, 0.08846483, 3.06182995,
        0.08962021, 3.24797673]),
 'std_fit_time': array([0.00274989, 0.06203093, 0.00577649, 0.03257122, 0.0028639 ,
        0.1229195 , 0.00374326, 0.31350334, 0.0036637 , 0.39581929,
        0.00415339, 0.29082806, 0.00668985, 0.41975789, 0.00415141,
        0.50047168, 0.0068076 , 0.47126212, 0.00512724, 0.56990116,
        0.00731445, 0.37601198]),
 'mean_score_time': array([0.02847424, 0.00945621, 0.02868042, 0.00903015, 0.02727604,
        0.00937676, 0.02641678, 0.00898161, 0.02666888, 0.00818119,
        0.02619328, 0.00862446, 0.02840719, 0.00862079, 0.02717133,
        0.00882149, 0.02553   , 0.00860419, 0.02713594, 0.00857358,
        0.02667871, 0.00886159]),
 'std_score_time': array([0.00

In [53]:
df_1 = pd.DataFrame(clf.cv_results_)
df_1


mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.065102      0.002960         0.027568        0.001530       1   
1        0.041316      0.002884         0.009129        0.001095       1   
2        0.058831      0.002584         0.026496        0.001268      10   
3        0.042802      0.000233         0.008554        0.000136      10   
4        0.055880      0.001838         0.025554        0.002592      20   
5        0.043580      0.002520         0.008883        0.000306      20   
6        0.058626      0.001567         0.026135        0.001079      30   
7        0.041604      0.001028         0.008139        0.000603      30   
8        0.059201      0.001281         0.026442        0.001250      40   
9        0.045576      0.001518         0.007866        0.000226      40   
10       0.056253      0.001383         0.024922        0.001354      50   
11       0.044668      0.001072         0.008148        0.000822      50   
12       0.053714      0.003010         0.023361        0.000285      60   
13       0.043533      0.001931         0.007741        0.000941      60   
14       0.055960      0.005076         0.024415        0.001114      70   
15       0.045217      0.001798         0.007497        0.000125      70   
16       0.053080      0.002173         0.024089        0.001308      80   
17       0.048449      0.004729         0.007668        0.000704      80   
18       0.058024      0.002097         0.024487        0.000941      90   
19       0.046813      0.003732         0.007317        0.000288      90   
20       0.056720      0.003321         0.023705        0.000965     100   
21       0.049021      0.001008         0.008124        0.000730     100   

   param_kernel                          params  split0_test_score  \
0           rbf       {'C': 1, 'kernel': 'rbf'}           0.240741   
1        linear    {'C': 1, 'kernel': 'linear'}           0.229630   
2           rbf      {'C': 10, 'kernel': 'rbf'}           0.303704   
3        linear   {'C': 10, 'kernel': 'linear'}           0.292593   
4           rbf      {'C': 20, 'kernel': 'rbf'}           0.325926   
5        linear   {'C': 20, 'kernel': 'linear'}           0.359259   
6           rbf      {'C': 30, 'kernel': 'rbf'}           0.348148   
7        linear   {'C': 30, 'kernel': 'linear'}           0.388889   
8           rbf      {'C': 40, 'kernel': 'rbf'}           0.370370   
9        linear   {'C': 40, 'kernel': 'linear'}           0.414815   
10          rbf      {'C': 50, 'kernel': 'rbf'}           0.370370   
11       linear   {'C': 50, 'kernel': 'linear'}           0.444444   
12          rbf      {'C': 60, 'kernel': 'rbf'}           0.381481   
13       linear   {'C': 60, 'kernel': 'linear'}           0.455556   
14          rbf      {'C': 70, 'kernel': 'rbf'}           0.396296   
15       linear   {'C': 70, 'kernel': 'linear'}           0.451852   
16          rbf      {'C': 80, 'kernel': 'rbf'}           0.400000   
17       linear   {'C': 80, 'kernel': 'linear'}           0.455556   
18          rbf      {'C': 90, 'kernel': 'rbf'}           0.400000   
19       linear   {'C': 90, 'kernel': 'linear'}           0.462963   
20          rbf     {'C': 100, 'kernel': 'rbf'}           0.403704   
21       linear  {'C': 100, 'kernel': 'linear'}           0.481481   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.314815           0.437037           0.414815   
1            0.274074           0.418519           0.359259   
2            0.392593           0.474074           0.462963   
3            0.377778           0.481481           0.433333   
4            0.418519           0.503704           0.492593   
5            0.400000           0.500000           0.414815   
6            0.444444           0.500000           0.492593   
7            0.429630           0.518519           0.429630   
8            0.448148           0.500000           0.492593   
9            0

In [54]:
df_1[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.377778
1        1       linear         0.348148
2       10          rbf         0.408148
3       10       linear         0.407407
4       20          rbf         0.451111
5       20       linear         0.427407
6       30          rbf         0.460000
7       30       linear         0.446667
8       40          rbf         0.465185
9       40       linear         0.460000
10      50          rbf         0.467407
11      50       linear         0.468148
12      60          rbf         0.474074
13      60       linear         0.478519
14      70          rbf         0.474074
15      70       linear         0.482222
16      80          rbf         0.478519
17      80       linear         0.491852
18      90          rbf         0.483704
19      90       linear         0.494815
20     100          rbf         0.489630
21     100       linear         0.502222

In [55]:
clf.best_score_

0.5022222222222222

In [56]:
clf.best_params_

{'C': 100, 'kernel': 'linear'}

Randmized search for hyper parameters

In [57]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': np.linspace(0,500,50),
        'kernel':['rbf','linear']
    },
    cv=5, #cross validation
    return_train_score=False,
    n_iter=21
)
rs.fit(X, df['type_of_opt'])
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/svm/_base.py", line 226, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/svm/_base.py", line 277, in _dense_fit
    self._probB, self.fit_status_ = libsvm.fit(
  File "sklearn/svm/_libsvm.pyx", line 192, in sklearn.svm._libsvm.fit
ValueError: C <= 0

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/saleksegid/miniconda3/lib/python3.8/site-packages/

param_C param_kernel  mean_test_score
0   295.918367          rbf         0.518519
1   275.510204       linear         0.527407
2    40.816327       linear         0.461481
3        500.0          rbf         0.525926
4   142.857143          rbf         0.490370
5   469.387755          rbf         0.524444
6   346.938776          rbf         0.522963
7          0.0          rbf              NaN
8    377.55102          rbf         0.525185
9   275.510204          rbf         0.514815
10  306.122449       linear         0.527407
11  326.530612          rbf         0.523704
12  397.959184       linear         0.526667
13  244.897959       linear         0.525185
14  234.693878          rbf         0.506667
15   71.428571       linear         0.482222
16   81.632653          rbf         0.477778
17  336.734694          rbf         0.525185
18   438.77551       linear         0.528148
19    61.22449       linear         0.478519
20  469.387755       linear         0.527407

In [59]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

Choosing the best model

In [298]:
model_params = {
    'svm':{
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': np.linspace(0,1000,50),
            'kernel': ['rbf','linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [0,5,10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': np.linspace(0,1000,50)
        }
    }
}

In [300]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X, df['type_of_opt'])
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/svm/_base.py", line 226, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/svm/_base.py", line 277, in _dense_fit
    self._probB, self.fit_status_ = libsvm.fit(
  File "sklearn/svm/_libsvm.pyx", line 192, in sklearn.svm._libsvm.fit
ValueError: C <= 0

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/saleksegid/miniconda3/lib/python3.8/site-packages/

/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.36592593 0.42296296 0.37259259 0.44740741
 0.38518519 0.46740741 0.38740741 0.48148148 0.39111111 0.49555556
 0.39777778 0.50444444 0.39777778 0.50888889 0.40296296 0.51481481
 0.40518519 0.52074074 0.40518519 0.52296296 0.40444444 0.52666667
 0.40814815 0.53925926 0.41259259 0.53481481 0.4162963  0.53925926
 0.41925926 0.5437037  0.42740741 0.54592593 0.4237037  0.54592593
 0.42518519 0.54444444 0.42814815 0.54666667 0.43037037 0.54074074
 0.43037037 0.54148148 0.43037037 0.54518519 0.43259259 0.54518519
 0.43481481 0.54666667 0.43777778 0.54592593 0.43851852 0.54518519
 0.43925926 0.54518519 0.43851852 0.54592593 0.4362963  0.54518519
 0.43777778 0.54444444 0.43851852 0.54666667 0.43703704 0.54666667
 0.43703704 0.54444444 0.43703704 0.54296296 0.43777778 0.54518519
 0.4362963  0.54518519 0.43703704 0.548

/Users/saleksegid/miniconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.40814815 0.41185185 0.42296296 0.42592593 0.43259259
 0.4362963  0.44       0.44296296 0.44518519 0.44592593 0.44740741
 0.44814815 0.44888889 0.45259259 0.45407407 0.45407407 0.45481481
 0.4562963  0.45703704 0.45851852 0.46148148 0.46296296 0.4637037
 0.46444444 0.46592593 0.46888889 0.47037037 0.47111111 0.47111111
 0.47111111 0.47185185 0.47259259 0.47259259 0.47259259 0.47185185
 0.47185185 0.47407407 0.47407407 0.47555556 0.4762963  0.47555556
 0.47703704 0.47703704 0.47703704 0.47703704 0.47925926 0.47925926
 0.47925926 0.48      ]
  warnings.warn(


In [ ]:
df_2 = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df_2

In [67]:
### abovel showes that svm has the higher score, therefore the better model

In [63]:
models = (svm.SVC(kernel='linear', C=100),
        svm.LinearSVC(C=100, max_iter=100),
         svm.SVC(kernel='rbf', gamma=0.8, C=100),
         svm.SVC(kernel='poly', degree=3, gamma='auto', C=100))

models = (clf.fit(X, y) for clf in models)

In [20]:
def kneighbors_graph(self):
    self.X_train = self.X_train.values
    A = neighbors.kneighbors_graph(self.X_train, 9, 'distance')
    plt.spy(A)
    plt.show

In [21]:
X = X
y = y
h = .02

cmap_light = ListedColormap(['#FFAAAA', '#AAFFAA', '#00AAFF'])
cmap_bold = ListedColormap(['#FF0000', '#00FF00', '#00AAFF'])

clf = neighbors.KNeighborsClassifier(K_neighbors, weights='distance')
clf.fit(X, y)

x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                     np.arange(y_min, y_max, h))

Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

Z = Z.reshape(xx.shape)
plt.figure()
plt.pcolormesh(xx, yy, Z, cmap=cmap_light)

plt.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_bold)
plt.xlim(xx.min(), xx.max())
plt.ylim(yy.min(), yy.max())
plt.title("1-Class classification (k = %i)" % (K_neighbors))
plt.show()

TypeError: '(slice(None, None, None), 0)' is an invalid key